# WhatATheme
markdown: kramdown

# URL of the Site
url: 'https://utkiraracircle.github.io'
assets_path: assets/

# Title of the Site
title: 東京大学きらら同好会
# Description of the Site
description: 東京大学きらら同好会は、まんがタイムきらら作品好きの東大生が集まる団体です。
# URL of Image of the Site
site-image: /assets/images/logolarge-white.png
# Keywords of the Site
site-keywords: 東京大学きらら同好会, きらら, まんがタイムきらら, サークル
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: ../images/hero.jpg # relative path from /assets/css

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
# email: ''
# facebook_username: ''
twitter_username: UTKiraraCircle
# Google Analytics
google-analytics: ''

# Name of the Author
author-name: 東京大学きらら同好会
# URL for the Image of the Author
author-image: images/logo.png
# 60 Words About the Author
author-about: |-
  こんにちは！東京大学きらら同好会です！！<br>
  当団体は、まんがタイムきらら作品好きの東大生が集まる、<br>
  2021年春に発足したばかりの新しい団体です。
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://twitter.com/UTKiraraCircle

urls:
  form: https://forms.gle/wV19XLcv38hD6tqd9
  blog: https://utkiraracircle.hatenablog.com/
  official-twitter: https://twitter.com/UTKiraraCircle

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "posts/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
